name: Build Authentik Plugin

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build the Plugin
        run: |
          bash ./build.sh

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: plugin/authentik-plugin-amd64.so
          generate_release_notes: true
